{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "ado-git-migration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ado-git-migration.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "ado-git-migration.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
  {{- range .Values.keda.triggers }}
  - type: {{ .type }}
    metadata:
      {{- toYaml .metadata | nindent 6 }}
  {{- end }}
{{- end }}