---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migration.ado-to-git-migration.io
  resources:
  - adodiscoveries
  - adotogitmigrations
  - batchmigrations
  - githubprojects
  - migrationjobs
  - monorepomigrations
  - pipelinetoworkflows
  - repositorymigrations
  - workitemmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.ado-to-git-migration.io
  resources:
  - adodiscoveries/finalizers
  - adotogitmigrations/finalizers
  - batchmigrations/finalizers
  - githubprojects/finalizers
  - migrationjobs/finalizers
  - monorepomigrations/finalizers
  - pipelinetoworkflows/finalizers
  - workitemmigrations/finalizers
  verbs:
  - update
- apiGroups:
  - migration.ado-to-git-migration.io
  resources:
  - adodiscoveries/status
  - adotogitmigrations/status
  - batchmigrations/status
  - githubprojects/status
  - migrationjobs/status
  - monorepomigrations/status
  - pipelinetoworkflows/status
  - workitemmigrations/status
  verbs:
  - get
  - patch
  - update
