apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reposhift-platform
  namespace: argocd
spec:
  project: github-migrator
  source:
    repoURL: https://github.com/tesserix/reposhift.git
    path: charts/reposhift-platform
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: mode
          value: selfhosted
        - name: adminToken
          value: reposhift-admin-2026
        - name: postgresPassword
          value: changeme
        - name: postgresql.host
          value: "postgresql.postgresql-global.svc.cluster.local"
        - name: postgresql.sslmode
          value: disable
        - name: istio.enabled
          value: "true"
        - name: istio.host
          value: repomigrator.tesserix.app
        - name: cors.allowedOrigins
          value: "https://repomigrator.tesserix.app,http://localhost:3005"
  destination:
    server: https://kubernetes.default.svc
    namespace: git-migrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
