apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reposhift-platform
  namespace: argocd
spec:
  project: github-migrator
  source:
    repoURL: https://github.com/tesserix/reposhift.git
    path: charts/reposhift-platform
    targetRevision: main
    helm:
      valueFiles:
        - values-selfhosted.yaml
      parameters:
        - name: mode
          value: selfhosted
        - name: adminToken
          value: reposhift-admin-2026
        - name: postgresPassword
          value: changeme
        - name: postgresql.host
          value: "10.117.240.3"
        - name: postgresql.sslmode
          value: require
  destination:
    server: https://kubernetes.default.svc
    namespace: git-migrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
