apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reposhift-operator
  namespace: argocd
spec:
  project: github-migrator
  source:
    repoURL: https://github.com/tesserix/reposhift.git
    path: charts/ado-git-migration
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: persistence.storageClassName
          value: standard-rwo
        - name: persistence.size
          value: "10Gi"
        - name: image.repository
          value: ghcr.io/tesserix/reposhift
        - name: imagePullSecrets[0].name
          value: ghcr-secret
        - name: postgresql.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: git-migrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
