apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reposhift-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tesserix/reposhift.git
    path: charts/reposhift-web
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: git-migrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
