apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reposhift-web.fullname" . }}
  labels:
    {{- include "reposhift-web.labels" . | nindent 4 }}
data:
  PLATFORM_API_URL: {{ .Values.platformApiUrl | quote }}
  PORT: {{ .Values.port | quote }}
  HOSTNAME: "0.0.0.0"
  NODE_ENV: "production"
