{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "reposhift-web.fullname" . }}
  labels:
    {{- include "reposhift-web.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - headers:
            upgrade:
              exact: websocket
      route:
        - destination:
            host: {{ include "reposhift-web.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.port }}
      timeout: 3600s
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "reposhift-web.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.port }}
      timeout: 30s
{{- end }}
