apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reposhift-platform.fullname" . }}
  labels:
    {{- include "reposhift-platform.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.port | quote }}
  POSTGRES_HOST: {{ .Values.postgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_DATABASE: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_SSLMODE: {{ .Values.postgresql.sslmode | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
  OPERATOR_URL: {{ .Values.operatorURL | quote }}
  K8S_NAMESPACE: {{ .Values.k8sNamespace | quote }}
