apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reposhift-platform.fullname" . }}
  labels:
    {{- include "reposhift-platform.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | default "" | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.encryptionKey | default "" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | default "" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.github.clientSecret | default "" | b64enc | quote }}
  ADMIN_TOKEN: {{ .Values.adminToken | default "" | b64enc | quote }}
