apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reposhift-platform.fullname" . }}
  labels:
    {{- include "reposhift-platform.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.adminToken | default "" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | default "" | b64enc | quote }}
