apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reposhift-platform.fullname" . }}
  labels:
    {{- include "reposhift-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false
